### ISSUE TITLE
Maven Build not running JUnits and hence test report not being generated.

### ISSUE THREAD

**Issue by tilaksatra** [mohitsoni2111/jobPortal#32]
<img width="960" alt="image" src="https://user-images.githubusercontent.com/43577257/194732181-a2252c90-e1ea-4d05-a2fd-4f65f820b48d.png">

**Comment by akshat22** [comment]
I see you have solved this issue by including junit-vintage-engine dependency as it is required for JUnit4 tests to be captured under evidences. Hence, I'm closing this issue.
